-- 05_sales_report.sql
-- Goal:
-- Build a sales report by track, album, artist, and genre
-- This demonstrates:
-- 1. Multiple table joins
-- 2. Revenue calculation
-- 3. Aggregation for reporting

SELECT
    ar.Name AS ArtistName,
    al.Title AS AlbumTitle,
    g.Name AS GenreName,
    t.Name AS TrackName,

    -- Total quantity sold for each track
    SUM(il.Quantity) AS TotalUnitsSold,

    -- Total revenue generated by each track
    ROUND(SUM(il.UnitPrice * il.Quantity), 2) AS TotalRevenue

FROM InvoiceLine il
JOIN Track t
    ON il.TrackId = t.TrackId
JOIN Album al
    ON t.AlbumId = al.AlbumId
JOIN Artist ar
    ON al.ArtistId = ar.ArtistId
JOIN Genre g
    ON t.GenreId = g.GenreId

GROUP BY
    ar.Name,
    al.Title,
    g.Name,
    t.Name

ORDER BY TotalRevenue DESC, TotalUnitsSold DESC;
